version: '3.8'

services:
  database:
    build:
      context: ./database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=movies_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app/backend
      - static_volume:/app/backend/static
      - media_volume:/app/backend/media
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/movies_db
      - DEBUG=False
      - SECRET_KEY=your_secret_key_here
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/static:/usr/share/nginx/html/static
      - ./frontend/static_root:/usr/share/nginx/html/static_root
      - ./frontend/media:/usr/share/nginx/html/media
      - ./frontend/templates:/usr/share/nginx/html/templates
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume: