# Generated by Django 5.0.2 on 2025-06-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_download',
            field=models.BooleanField(default=False),
        ),
    ]
