# Generated by Django 5.2.2 on 2025-06-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_category_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='autoplay_videos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_language',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_new_releases',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_recommendations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_subtitles',
            field=models.BooleanField(default=False),
        ),
    ]
